### PR TITLE
fix(server): fix parsing lyrics in uncommon format

### PR DESCRIPTION
**Pull request by yume-chan**
The lyric of song [仲村芽衣子 - Scarlet Faith](https://music.163.com/#/song?id=28812025) is:

```text
[00:00.000] 作词 : 仲村芽衣子
[00:00.000] 作曲 : 水夏える
[0:00.000]
[0:14.880]離れて君を手繰るその指は
[0:18.480]ただ儚い時を辿って
[0:21.280]終わらない夢を彷徨い続けた
[0:24.770]迷い無き僕の目で
[0:28.000]熱き鼓動を響かせて
[0:31.400]
[0:37.750]
[0:43.910]この両手が歪ませた
[0:47.080]罪と制裁の狭間で
[0:50.230]塵に紛れて 錆び付く刃
[0:55.250]
[0:56.330]何が正義であるべきか
[0:59.750]その目で見つめた物が
[1:03.000]答えじゃないのならば
[1:06.100]何を信じればいい？
[1:09.530]
[1:10.540]A change out その日 was my sanctuary
[1:14.080]その声が胸を焦がして
[1:16.880]走り出す影が届かない場所へ
[1:20.450]消えてしまう前に 抱きしめに行く
[1:23.230]
[1:23.840]離れて君を手繰るその指は
[1:26.800]ただ儚い時を辿って
[1:29.620]終わらない夢を彷徨い続けた
[1:33.140]迷い無き僕の目で
[1:36.370]熱き鼓動を響かせて
[1:39.740]
[1:45.840]まだ芽生えたての種が
[1:49.090]古き戦場に塗れて
[1:52.210]息を殺して流した涙
[1:57.220]
[1:58.380]やがて事実は凌がれて
[2:01.800]行き場のないこの声が
[2:04.940]世界を枯らすのなら
[2:08.130]壊してしまえばいい
[2:11.520]
[2:12.520]Another to change out my precious life and history
[2:16.100]未来を抜き 今スピード上げ
[2:18.880]届かないなんて諦める前に
[2:22.450]握り締めた剣 振りかざし続け
[2:25.250]
[2:25.820]終わらない夢を彷徨い続けて
[2:28.800]僕の目は炎宿して
[2:31.570]空を舞う灰が降り注いでいた
[2:35.120]味気ないこの世界
[2:38.340]君という光で溶かして
[2:41.730]
[2:49.690]...music...
[3:05.570]
[3:08.140]佇むものは星の数ほどに
[3:11.730]発つ者は一握りだけ
[3:14.480]意味があるようで でも見つからずに
[3:18.010]進む戦火の海駆け抜けた 降り注ぐ灰
[3:22.460]
[3:23.040]A change out その日 was my sanctuary
[3:25.980]その声が胸が焦がして
[3:28.790]走り出す影が届かない場所へ
[3:32.340]消えてしまう前に 抱きしめに行く
[3:35.100]
[3:35.750]まだ終わらない 手繰るその指は
[3:38.700]ただ儚い時を辿って
[3:41.500]守りたいだから 刃をかざした
[3:45.070]迷い無き僕の目で
[3:48.270]願うのはみな同じ
[3:51.250]そうどこまでも切り裂いて
[3:56.430]
[4:09.160]-END-
```

From the third line, the timestamps are in `[0:00.000]` format, instead of the commonly found `[00:00.000]`.

With current parsing logic, all those lines will be discarded.

image

This PR allows minute number in any length, thus fixing parsing such lines. It also trims leading and trailing spaces from each line to better align with official web player.

image

### CODE REVIEW

**Comment by yume-chan** [comment]
Some random things:

I really don't like you writing TypeScript in Rust flavor.
My compiled server.js stuck at Song: Loading at startup, with no error in stderr. After manually pick one to play, it appears to be playing, but without sound.

**Comment by YXL76** [comment]
> Some random things:
> 
> * I really don't like you writing TypeScript in Rust flavor.
> * My compiled `server.js` stucks at `Song: Loading` at startup, with no error in stderr. After manually pick one to play, it appears to be playing, but without sound.

1. Actually, I'm new to typescript and rust.
2. Do you mean there is no problem with the `server.js` compiled in github actions?

**Comment by yume-chan** [comment]
> Do you mean there is no problem with the `server.js` compiled in github actions?

Didn't try builds from GitHub Actions. Visual Studio Code Marketplace released version is ok.

My steps:

```
git clone ...
git checkout v8.3.8
yarn
yarn generate-css
yarn build
cd crates/native
cargo build
cd ../..
mkdir build
cp crates/native/index.node build/win32-x86.node
node dist/server.js
```

Then activate official release version 8.3.8, it will connect to my dev server.

But initially it looks like this:

image

The queue is empty (should be daily recommended songs), and status bar shows "Song: Loading"

There is no error in `node dist/server`.

By selecting a song in my favorite playlist, it starts "playing", just has no sound

image

I'm not sure:

* Why does it require installing LLVM?
    https://github.com/YXL76/cloudmusic-vscode/blob/9cf8fd7db8819a74903bb182531a02c335ef4722/.github/workflows/release.yml#L100-L104
* Does neon compile for Electron or Node.js? I see you enabled the `n-api` feature, does the produced binary support all Node.js versions and variants because of it?
* What does `wasi` package do? wasm-pack installation is broken now on Windows so I didn't build it, and it seems like still working fine.
    https://github.com/YXL76/cloudmusic-vscode/blob/9cf8fd7db8819a74903bb182531a02c335ef4722/.github/workflows/release.yml#L185-L186

A development guide will be extremely helpful.

**Comment by YXL76** [comment]
@yume-chan 

1. The server starts before the client, and the client thinks another client has existed before, so it did not initialize (e.g., getting recommended song lists, setting volume). If you set volume manually, it will have sound.
2. It needs llvm for `bindgen`.
3. You can check the [Node-API version matrix](https://nodejs.org/api/n-api.html#n_api_node_api_version_matrix) for the supported versions.
4. `Wasi` is of no use right now, it will be used in `v9.x.x`.

**Comment by yume-chan** [comment]
> and the client thinks another client has existed before, so it did not initialize

Understood. There should be a better way to debug the server, for example allowing specifying custom server path and pass `--inspect`/`--inspect-brk` when forking the server. Like how TypeScript language feature extension did https://github.com/microsoft/vscode/blob/39510d4778bcd683a7b76461785fe0ee966eaf1a/extensions/typescript-language-features/src/tsServer/serverProcess.electron.ts#L178-L182

> It needs llvm for `bindgen`.

Where is it used? I can build everything following workflow file fine on Windows.

**Comment by YXL76** [comment]
> Where is it used? I can build everything following workflow file fine on Windows.

Actually, I don't know. But building it in Github Action will fail without llvm. 

https://github.com/neon-bindings/neon/blob/65c076829d403f04cd3ea7a5f0f3457ad525e955/.github/workflows/windows.yml#L36-L40

**Pull request merged**
